{{- if eq .Requirements.webhook "prow" }}
enabled: true
{{- else }}
enabled: false
{{- end }}

hmacToken: "{{ .Parameters.prow.hmacToken }}"
oauthToken: "{{ .Parameters.pipelineUser.token }}"
user: "{{ .Parameters.pipelineUser.username }}"

buildnum:
  enabled: false
pipelinerunner:
  enabled: "true"
  args:
  - controller
  - pipelinerunner
  - --use-meta-pipeline=false
tillerNamespace: ""

sinker:
  replicaCount: 0
